name: Build

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows

          - os: ubuntu-latest
            platform: linux

          - os: macos-latest
            platform: macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install scons

      - name: Build Debug
        run: scons platform=${{ matrix.platform }} target=template_debug

      - name: Build Release
        run: scons platform=${{ matrix.platform }} target=template_release

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: godotopus-${{ matrix.platform }}
          path: build/addons/godotopus/bin
